version: '3.8'

services:
  nginx:
    image: nginx:1.19-alpine
    container_name: irb.nginx
    restart: on-failure
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./:/var/www/
      - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-compose/nginx/log:/var/log/nginx
    depends_on:
      - php-fpm
    networks:
      - default

  php-fpm:
    build:
      context: docker-compose/php-fpm
    container_name: irb.php-fpm
    restart: on-failure
    volumes:
      - ./:/var/www/
      - ./docker-compose/php-fpm/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www
    networks:
      - default

  mysql:
    image: mysql:8
    container_name: irb.mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker-compose/mysql/data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    networks:
      - default

  adminer:
    image: adminer:standalone
    container_name: irb.adminer
    restart: on-failure
    links:
      - mysql
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - mysql
    networks:
      - default

networks:
  default:
    driver: bridge
